from methods.utils import find_closest_match

SHEET_NAME = "Award - Template"
SHEET_COLUMNS = [
    "projectLegacyNumber",
    "proposalLegacyNumber",
    "awardLegacyNumber",
    "status",
    "modificationNumber",
    "CUNY Campus",
    "Instrument Type",
    "Sponsor",
    "Unnamed: 8",
    "Sponsor Award Number",
    "Sponsor ALN",
    "Prime Sponsor",
    "Prime Sponsor Award Number",
    "Prime Sponsor ALN",
    "Title",
    "Award Notice Received",
    "Project Start Date",
    "Project End Date",
    "Award Close Date",
    "Program Name",
    "Proposal Type",
    "Activity Type",
    "John Jay Centers",
    "Admin Unit Name",
    "Admin Unit",
    "Discipline",
    "Description",
    "Abstract",
    "Proposal Key Words",
    "Award Legacy Number",
    "Account Legacy Number",
    "Legacy Modification Type",
    "Sabbatical YN",
    "Sabbatical Details",
    "Number of Budget Periods",
    "Indirect Rate Cost Type",
    "IDC Rate",
    "IDC Cost Type Explanation",
    "Total Direct Costs",
    "Total Indirect Costs",
    "Total Sponsor Costs",
    "Total Awarded Direct Costs",
    "Total Awarded Indirect Costs",
    "Total Expected Amount",
    "Obligated Direct Costs",
    "Obligated Indirect Costs",
    "Obligated Amount",
    "Anticipated Direct Costs",
    "Anticipated Indirect Costs",
    "Anticipated Amount",
    "Yr 1 Direct Costs",
    "Year 1 Indirect Costs",
    "Year 1 Total Costs",
    "Awarded Yr 1 Direct Costs",
    "Awarded Yr 1 Indirect Costs",
    "Awarded Yr 1 Total Costs",
    "Yr 2 Direct Costs",
    "Year 2 Indirect Costs",
    "Year 2 Total Costs",
    "Awarded Yr 2 Direct Costs",
    "Awarded Yr 2 Indirect Costs",
    "Awarded Yr 2 Total Costs",
    "Yr 3 Direct Costs",
    "Year 3 Indirect Costs",
    "Year 3 Total Costs",
    "Awarded Yr 3 Direct Costs",
    "Awarded Yr 3 Indirect Costs",
    "Awarded Yr 3 Total Costs",
    "Yr 4 Direct Costs",
    "Year 4 Indirect Costs",
    "Year 4 Total Costs",
    "Awarded Yr 4 Direct Costs",
    "Awarded Yr 4 Indirect Costs",
    "Awarded Yr 4 Total Costs",
    "Yr 5 Direct Costs",
    "Year 5 Indirect Costs",
    "Year 5 Total Costs",
    "Awarded Yr 5 Direct Costs",
    "Awarded Yr 5 Indirect Costs",
    "Awarded Yr 5 Total Costs",
    "Yr 6 Direct Costs",
    "Year 6 Indirect Costs",
    "Year 6 Total Costs",
    "Awarded Yr 6 Direct Costs",
    "Awarded Yr 6 Indirect Costs",
    "Awarded Yr 6 Total Costs",
    "Yr 7 Direct Costs",
    "Year 7 Indirect Costs",
    "Year 7 Total Costs",
    "Awarded Yr 7 Direct Costs",
    "Awarded Yr 7 Indirect Costs",
    "Awarded Yr 7 Total Costs",
    "Yr 8 Direct Costs",
    "Year 8 Indirect Costs",
    "Year 8 Total Costs",
    "Awarded Yr 8 Direct Costs",
    "Awarded Yr 8 Indirect Costs",
    "Awarded Yr 8 Total Costs",
    "Yr 9 Direct Costs",
    "Year 9 Indirect Costs",
    "Year 9 Total Costs",
    "Awarded Yr 9 Direct Costs",
    "Awarded Yr 9 Indirect Costs",
    "Awarded Yr 9 Total Costs",
    "Yr 10 Direct Costs",
    "Year 10 Indirect Costs",
    "Year 10 Total Costs",
    "Awarded Yr 10 Direct Costs",
    "Awarded Yr 10 Indirect Costs",
    "Awarded Yr 10 Total Costs",
    "Cost Share Required",
    "Internal Cost Share",
    "External Cost Share",
    "Total Cost Share",
    "Human Subjects",
    "Clinical Trial YN",
    "HE Application",
    "IRB Protocol Status",
    "HE Studies",
    "IRB Approval Date",
    "HE Reason",
    "Animal Subjects",
    "Animal Subjects Types",
    "AE Application",
    "Animal Subj Protocol Status",
    "AE Application Numbers",
    "IACUC Approval Date",
    "Animal Studies at College YN",
    "Animal Studies Off Site",
    "Animal Subjects Euthanized YN",
    "Euthanasia Consistent AVMA YN",
    "AE Species Involved",
    "AE Application Reason",
    "Hazardous Materials",
    "DURC YN",
    "Propriety Info Protection YN",
    "NDA YN",
    "Software Devpt Deliverable YN",
    "Intl Collab Partnership YN",
    "On Site",
    "On Site Location",
    "Off Site",
    "Off Site Location",
    "Subrecipient",
    "Subrecipient Names",
    "Add New Subrecipient",
    "Protocol Number",
    "Protocol Type",
    "Study Type",
    "Requires Registration",
    "Multi Site Study",
    "Study Phase",
    "Export Control",
    "EC Items",
    "EC Country",
    "International Travel",
    "International Travel Country",
    "EC Info Tech",
    "Encryption",
    "Publication Restriction",
    "Foreign Talent",
    "Foreign Location",
    "Foreign Activities",
    "Potential Patent",
    "IP Third Party",
    "IP Licensed",
    "SBIR STTR",
    "Terms and Conditions",
    "Restrictions",
    "Program Income Type",
    "Reporting Milestones",
    "Terms and Conditions - Other"
  ]

def determine_instrument_type(grant):
    valid_instrument_types = ['Grant', 'Contract', 'Cooperative Agreement', 'Incoming Subaward', 'NYC/NYS MOU - Interagency Agreement', 'PSC CUNY', 'CUNY Internal']
    
    project_instrument_type = grant['Program_Type']
    if project_instrument_type:
        if project_instrument_type in valid_instrument_types:
            return project_instrument_type
        else:
            closest_match = find_closest_match(project_instrument_type, valid_instrument_types)
            if closest_match:
                return closest_match
            else:
                raise Exception(f"Grant's instrument type '{project_instrument_type}' is not a valid choice.")
    else:
        raise Exception("Grant does not have an Instrument Type")

def awards_sheet_append(self, grant):
    sheet_df = self.generated_template_manager.df[SHEET_NAME]
    next_row = sheet_df.shape[0] + 1
  
    try:
        grant_instrument_type = determine_instrument_type(grant)
    except Exception as e:
        grant_instrument_type = None
        self.generated_template_manager.comment_manager.append_comment(SHEET_NAME, next_row, 7, e)
    
    self.generated_template_manager.append_row(SHEET_NAME, {
        "projectLegacyNumber": grant['Project_Legacy_Number'],
        "awardLegacyNumber": (str(grant['Grant_ID']) + "-award"),
        "status": "Active",   # Might need evaluation
        "modificationNumber": 0,
        "CUNY Campus": grant['Prim_College'],
        "Instrument Type": "",
        "Sponsor": "",
        "Sponsor Award Number": "",
        "Prime Sponsor": "",
        "Title": "",
        "Award Notice Recieved": "",
        "Project Start Date": "",
        "Project End Date": "",
        "Program Name": "",
        "Activity Type": "",
        "John Jay Centers": "",
        "Admin Unit": "",
        "Discipline": "",
        "Abstract": "",
        "Award Legacy Number": "",
        "Number of Budget Periods": "",
        "Indirect Rate Cost Type": "",
        "IDC Rate": "",
        "IDC Cost Type Explanation": "",
        "Total Awarded Direct Costs": "",
        "Total Awarded Indirect Costs": "",
        "Total Expected Amount": "",
        "Yr 1 Direct Costs": "",
        "Year 1 Indirect Costs": "",
        "Year 1 Total Costs": "",
        "Awarded Yr 1 Direct Costs": "",
        "Awarded Yr 1 Indirect Costs": "",
        "Awarded Yr 1 Total Costs": "",
        "Total Cost Share": "",
        "Human Subjects": "",
        "IRB Protocol Status": "",
        "IRB Approval Date": "",
        "Animal Subjects": "",
        "Hazardous Materials": "",
        "On Site": "",
        "Off Site": "",
        "Subrecipient": "",
        "Export Control": "",
        "Award Type": ""
    })